# See https://docs.aspect.build/workflows/configuration
---
workspaces:
  - .
  - examples/simple

tasks:
  - test:
      name: test-os:linux-bzl:latest
      queue: aspect-default
      hooks:
        - type: before_task
          command: |
            rm .bazelversion
            echo "USE_BAZEL_VERSION=latest" > .bazeliskrc

  - test:
      name: test-os:linux-bzl:8
      queue: aspect-default
      hooks:
        - type: before_task
          command: |
            rm .bazelversion
            echo "USE_BAZEL_VERSION=8.3.0" > .bazeliskrc

  - test:
      name: test-os:linux-bzl:7
      queue: aspect-default
      hooks:
        - type: before_task
          command: |
            rm .bazelversion
            echo "USE_BAZEL_VERSION=7.6.1" > .bazeliskrc
